fabulam/config/routes.rb
Fabulam::Application.routes.draw do
   root "home#home"
resources :journeys



match 'auth/:provider/callback', to: 'sessions#create', via: 'get'
match 'auth/failure', to: redirect('/'),  via: 'get'
match 'signout', to: 'sessions#destroy', via: 'get', as: 'signout'

end

fabulam/app/models/journey.rb
class Journey < ActiveRecord::Base
belongs_to :user
has_many :photos
validates :uid, presence: true


end

fabulam/app/models/photo.rb
class Photo < ActiveRecord::Base
belongs_to :journey
end

fabulam/app/models/user.rb
class User < ActiveRecord::Base
has_many :journeys

def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end

end

fabulam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

end

fabulam/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end
  
end

fabulam/app/controllers/journeys_controller niet werkend.rb
class JourneysController < ApplicationController
require 'fileutils'

 def index
 @current_user ||= User.find(session[:user_id]) if session[:user_id]
  @journey = Journey.where(uid:   current_user.uid)
 end
 
 def show
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  @journey = Journey.find(params[:id])
  @photo = Photo.where(jid: params[:id])  
  @hash = Gmaps4rails.build_markers(@photo) do |photo, marker|
    marker.lat photo.alt
    marker.lng photo.lon
  end
 end

 def new
 @current_user ||= User.find(session[:user_id]) if session[:user_id]
 @journey = Journey.new
 end

 def create

  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  @journey = Journey.new(uid: current_user.uid, name: params[:journey][:name])
  if @journey.save
    redirect_to journeys_path
  else
    render 'new'
  end
  directory_name = Rails.root.join('public', 'uploads', current_user.uid, Journey.last.id.to_s)
   Dir.mkdir(directory_name) unless File.exists?(directory_name)
   
   2.times do |i|
      @file = "image" + i
      if params[:journey][file]
        uploaded_io = params[:journey][file]
        File.open(Rails.root.join('public', 'uploads', current_user.uid, Journey.last.id.to_s, i +File.extname(uploaded_io.original_filename).to_s), 'wb') do |file|
          file.write(uploaded_io.read)
        end
        photo_name = '/uploads/'+ current_user.uid.to_s + '/' + Journey.last.id.to_s + '/' + i + File.extname(uploaded_io.original_filename).to_s 
        if Photo.create(jid: Journey.last.id, picture: photo_name, text: 'Dit is een voorbeeld tekst', alt: 51+i, lon:  4-i)          
        end 
      end  
   end
  
 end
  
 def edit
 @journey = Journey.find(params[:id])

 
 end
  
 def update
 @journey = Journey.find(params[:id])
 
  if @journey.update_attribute(:name, params[:journey][:name])
   redirect_to journeys_path
  else
   render 'edit'
  end
 end

 def destroy
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    naam = Rails.root.to_s+"/public/uploads/"+current_user.uid+"/"+params[:id]
    p naam
    @journey = Journey.find(params[:id])
    @journey.destroy
    FileUtils.remove_dir naam, true

    redirect_to journeys_path
 end

end

fabulam/app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
require 'fileutils'

 def index
 @current_user ||= User.find(session[:user_id]) if session[:user_id]
  @journey = Journey.where(uid:   current_user.uid)
 end
 
 def show
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  @journey = Journey.find(params[:id])
  @photo = Photo.where(jid: params[:id])  
  @hash = Gmaps4rails.build_markers(@photo) do |photo, marker|
    marker.lat photo.alt
    marker.lng photo.lon
  end
 end

 def new
 @current_user ||= User.find(session[:user_id]) if session[:user_id]
 @journey = Journey.new
 end

 def create

  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  @journey = Journey.new(uid: current_user.uid, name: params[:journey][:name])
  if @journey.save
    redirect_to journeys_path
  else
    render 'new'
  end
  directory_name = Rails.root.join('public', 'uploads', current_user.uid, Journey.last.id.to_s)
   Dir.mkdir(directory_name) unless File.exists?(directory_name)
   
   i = 1
   50.times do |x|
      if params[:journey]["image#{i}"]
   
      photo_id = i.to_s
      photo_place = "image"+i.to_s
      
            uploaded_io = params[:journey]["image#{i}"]
            File.open(Rails.root.join('public', 'uploads', current_user.uid, Journey.last.id.to_s, photo_id  +File.extname(uploaded_io.original_filename).to_s), 'wb') do |file|
              file.write(uploaded_io.read)
            end
            photo_name = '/uploads/'+ current_user.uid.to_s + '/' + Journey.last.id.to_s + '/' + photo_id + File.extname(uploaded_io.original_filename).to_s 
            if Photo.create(jid: Journey.last.id, picture: photo_name, text: 'Dit is een voorbeeld tekst', alt: 51-i, lon: 4+i)          
            end 
       i = i +1     
      end 
    end

 end
  
 def edit
 @journey = Journey.find(params[:id])

 
 end
  
 def update
 @journey = Journey.find(params[:id])
 
  if @journey.update_attribute(:name, params[:journey][:name])
   redirect_to journeys_path
  else
   render 'edit'
  end
 end

 def destroy
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    naam = Rails.root.to_s+"/public/uploads/"+current_user.uid+"/"+params[:id]
    p naam
    @journey = Journey.find(params[:id])
    @journey.destroy
    FileUtils.remove_dir naam, true

    redirect_to journeys_path
 end

end

fabulam/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to "http://localhost:3000/journeys"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

fabulam/app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
 @current_user ||= User.find(session[:user_id]) if session[:user_id]
  @journey = Journeys.where(uid:   current_user.uid)
 end
 
 def show
  @journey = Journeys.find(params[:id])
 end

 def new
 @journey = Journeys.new
 end

 def create
  ##@current_user ||= User.find(session[:user_id]) if session[:user_id]
  #@journey = Journeys.new
  #@journey.uid = "100002113682553"
  #@journey.name = "Test" 
  #@journey.save
 end
  
 def edit
 end
  
 def update
 end

 def destroy
 end

end

fabulam/app/helpers/application_helper.rb
module ApplicationHelper
end

fabulam/app/views/home/home.html.erb
<!DOCTYPE html>
<html>
<body>

<h1>Login page</h1>


<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>! </br>
    <h1><%= link_to "Sign out", signout_path, id: "sign_out" %></h1>      
      <h1><%= link_to  "Journeys", journeys_path %> </h1>
  <% else %>
  
  <h1>  <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></h1>

  <% end %>
</div>

</body>
</html>

fabulam/app/views/journeys/edit.html.erb
<!DOCTYPE html>
<html>
<body>
	<div id="user_nav">
	  <% if current_user %>
		Signed in as <strong><%= current_user.name %></strong>!
		<%= link_to "Sign out", signout_path, id: "sign_out" %>
	  <% else %>
		<%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
	  <% end %>

	</div>

	<div id="travels">
	Pas hieronder je reisnaam aan!
	
	<%= form_for @journey do |f| %>
	    <p>
		<%=  f.label :name %><br/>
		<%= f.text_field :name %><br/>
	    <%= f.file_field :image %>

		</p>
		<p>
		<%= f.submit "Submit" %>
		</p>
	<% end %>
</body>
</html>

fabulam/app/views/journeys/index.html.erb
<!DOCTYPE html>
<html>
<body>
	<div id="user_nav">
	  <% if current_user %>
		Signed in as <strong><%= current_user.name %></strong>!
		<%= link_to "Sign out", signout_path, id: "sign_out" %>
	  <% else %>
		<%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
	  <% end %>
	</div>

	<div id="travels">
	<h1>Hieronder al je reizen!</h1>
	<% @journey.each do |journey| %>
        <h2><%=  link_to journey.name, journey %></h2>
        <div id= "links">
        <%= link_to  "edit", edit_journey_path(journey) %>
        <%= button_to 'Delete', journey, :method => :delete %> </p>
        </div>
	<% end %> 
	</div>
	
	<h2><%= link_to "Add a new journey" , new_journey_path %> </h2>

</body>
</html>

fabulam/app/views/journeys/new.html.erb
<!DOCTYPE html>
<html>
<body>
    <div>
	<h1> Maak hieronder een nieuwe reis aan! </h1>
    <h1><%= link_to "Journeys", journeys_path  %> </h1>
	
	<%= form_for @journey ,:url => { :action => "create"}, :html => { :multipart => true, :id => "form_name"} do |f| %>﻿
	    <p>
		 <%=  f.label :name %><br/>
		 <%= f.text_field :name %><br/>
		</p>
		<p>
		   <input type="button" onclick="addfile();" value="Voeg meer foto's toe!" />
		</p>
		<p>
		<%= f.submit "Submit" %>
		</p>
        </div>

	<% end %>

	</div>
</body>
</html>

fabulam/app/views/journeys/show.html.erb
<!DOCTYPE html>

<html>

<body>


	<div id="travels">
	<h1><%= @journey.name %></h1>
	<h1><%= link_to  "Journeys", journeys_path %> </h1>
	
<div style='width: 800px;'>
  <div id="multi_markers" style='width: 800px; height: 400px;'></div>
</div>
    

</div> 
	
<script type="text/javascript">

var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'multi_markers'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

	
	<div id="photos">
	Hieronder al je fotos en verhalen </br>
	<ul class="hoverbox">
	<% @photo.each do |photo| %>
     <li> <%= image_tag photo.picture, :class => "preview"  %></li>
	<% end %> 
	</ul>
	</div>
	

	

</body>
</html>

fabulam/app/views/journeys/user.html.erb
<!DOCTYPE html>
<html>
<body>
	<div id="user_nav">
	  <% if current_user %>
		Signed in as <strong><%= current_user.name %></strong>!
		<%= link_to "Sign out", signout_path, id: "sign_out" %>
	  <% else %>
		<%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
	  <% end %>
	</div>

	<div id="travels">
	Hieronder al je reizen!
	<% @travels.each do |travel| %>
	  <ul>
        <li><%= travel.name %></td>
      </ul>
	<% end %> 
	</div>
	<div id="travelnew">
	Maak hieronder een nieuwe reis aan!
	
		<%= form_for(@journey) do |f| %>
			Naam van de reis! : <%= f.text_field :name %><br />
			<%= f.submit %>
		<% end %>
	</div>
</body>
</html>

fabulam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fabulam</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<%= javascript_include_tag 'jquery', 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>